site_name: Vortex Documentation
copyright: Copyright &copy; 2024 NightBlue. All rights reserved.

theme:
  name: material
  logo: assets/vortex.png
  favicon: assets/vortex.png
  features:
  - navigation.tabs
  palette:
    primary: white
    accent: teal

nav:
- 'General':
  - 'index.md'
- 'API':
  - 'api/index.md'

extra:
  generator: false

markdown_extensions:
- admonition
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- attr_list
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- md_in_html
- footnotes
